optimizer: GRADIENT_DESCENT
stopcondition {
  all_processed: false
  steps: 1000000
}
train: true
batchsize: 100
data_proto: "/home/mbrubake/Projects/deepnet/deepnet/examples/data/mnist/mnist.pbtxt"
eval_after: 1000
checkpoint_after: 100000
checkpoint_directory: "/home/mbrubake/Projects/deepnet/deepnet/examples/data/tmp"
randomize: true
show_after: 0
