name: "mass_roads_patches"
gpu_memory: "500M"
main_memory: "4G"

data {
  name: "train_data"
  file_pattern: "/home/mbrubake/Projects/map_prior/mass_roads_patches/train/sat_*.npy"
  dimensions: 12288
  size: 8568832
  stats_file:  "/home/mbrubake/Projects/map_prior/mass_roads_patches/train/sat_patch_stats.npz"
}
data {
  name: "train_labels"
  file_pattern: "/home/mbrubake/Projects/map_prior/mass_roads_patches/train/map_*.npy"
  dimensions: 256
  size: 8568832
}

data {
  name: "validation_data"
  file_pattern: "/home/mbrubake/Projects/map_prior/mass_roads_patches/valid/sat_*.npgz"
  dimensions: 12288 
  size: 113400
  stats_file:  "/home/mbrubake/Projects/map_prior/mass_roads_patches/train/sat_patch_stats.npz"
}
data {
  name: "validation_labels"
  file_pattern: "/home/mbrubake/Projects/map_prior/mass_roads_patches/valid/map_*.npgz"
  dimensions: 256
  size: 113400
}

data {
  name: "test_data"
  file_pattern: "/home/mbrubake/Projects/map_prior/mass_roads_patches/test/sat_*.npgz"
  dimensions: 12288 
  size: 393216
  stats_file:  "/home/mbrubake/Projects/map_prior/mass_roads_patches/train/sat_patch_stats.npz"
}
data {
  name: "test_labels"
  file_pattern: "/home/mbrubake/Projects/map_prior/mass_roads_patches/test/map_*.npgz"
  dimensions: 256
  size: 393216
}

