optimizer: PCD
stopcondition {
  all_processed: false
  steps: 600000
}
train: true
batchsize: 100
data_proto: "/home/mbrubake/Projects/deepnet/deepnet/examples/data/mnist/mnist.pbtxt"
eval_after: 500
checkpoint_after: 100000
checkpoint_directory: "/home/mbrubake/Projects/deepnet/deepnet/examples/data/tmp"
randomize: false
show_after: 500
